services:
  # PostgreSQL-Datenbank
  cssystem-database:
    image: postgres:16
    container_name: cssystem-postgres
    restart: always
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    networks:
      - backend
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  # Strapi Backend
  cssystem-backend:
    build:
      context: .   # Dein Strapi Backend Ordner
    image: cssystem-backend:latest
    container_name: cssystem-backend
    ports: []
    networks:
      - backend
    depends_on:
      - cssystem-database
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      DATABASE_CLIENT: postgres
      DATABASE_HOST: cssystem-database
      DATABASE_PORT: 5432
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      APP_KEYS: ${APP_KEYS}
      API_TOKEN_SALT: ${API_TOKEN_SALT}
      ADMIN_JWT_SECRET: ${ADMIN_JWT_SECRET}
      JWT_SECRET: ${JWT_SECRET}

  # Frontend
  cssystem-website:
    build:
      context: ../CSSystem_Website
    image: cssystem-website:latest
    container_name: cssystem-website
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - cssystem-backend
    networks:
      - backend
    volumes:
      - /home/wwwuser/data/cert:/etc/nginx/cert:ro
      - /home/wwwuser/data/certbot/www/:/var/www/certbot:ro

networks:
  backend:
    driver: bridge

volumes:
  pgdata:
